### PR TITLE
fix(ci): Update storybook build configuration to use Webpack 5

### PR DESCRIPTION
**Pull request by ibolton336**
Fixes [this issue](https://stackoverflow.com/a/69699772) . Storybook was using Webpack 4 which fails to build on node 18 due to a [breaking change](https://stackoverflow.com/questions/69394632/webpak-build-failing-with-err-ossl-evp-unsupported). This PR changes the storybook configuration to use Webpack 5 which fixes the issue. 

There are also a few other changes included to fix linting issues ([prettier linting fix](https://github.com/migtools/lib-ui/pull/120/files#diff-35d3c81ce20949be44e744547c6d6aedc820498e5a2b1ab2b7cd776b54ba571cR13) and [ts linting fix](https://github.com/migtools/lib-ui/pull/120/files#diff-69887e3d2ce4b85d2700d5a672482bbafe7e9f0d4f16c0044c8da637e47fabd3R111)).

### CODE REVIEW

**Review by jmontleon — DISMISSED** [review]
ACK

**Comment by ibolton336** [comment]
@jmontleon Thanks for the review - I got it settled by setting the node version to 16.

**Comment by gildub** [comment]
@ibolton336, is there any reason/blocker to push it to version 18 as it's the current LTS version ?

**Comment by ibolton336** [comment]
@gildub Ended up being able to keep the LTS version as you suggested rather than downgrade and leave us vulnerable to security holes. The solution is in the description. Thanks!

**Review by mturley — APPROVED** [review]
LGTM

**Pull request merged**
